### ISSUE TITLE
Composer can't find roundcube/jqueryui?

### ISSUE THREAD

**Issue by peternemser** [tunis78/roundcube-hms_autoreply#1]
I am trying to add this plugin via composer and I get the following errors:

 Problem 1
    - The requested package roundcube/jqueryui could not be found in any version, there may be a typo in the package name.
  Problem 2
    - Installation request for tunis78/hms_autoreply ~1.1 -> satisfiable by tunis78/hms_autoreply[1.2].
    - tunis78/hms_autoreply 1.2 requires roundcube/jqueryui >=0.1 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Please advise on next steps to get this worked out.

**Comment by tunis78** [comment]
jqueryui is a part of roundcube now and does not exists as a plugin.
